### ISSUE TITLE
残留广告

### ISSUE THREAD

**Issue by ZYong9908** [klxiaoniu/ZuiYouHook#1]
![Screenshot_2023-01-14-21-30-44-906_cn xiaochuankeji tieba](https://user-images.githubusercontent.com/44081531/212474351-aca39c26-ad97-4288-81a6-b2cfb15bfe40.jpg)
![Screenshot_2023-01-14-21-30-21-580_cn xiaochuankeji tieba](https://user-images.githubusercontent.com/44081531/212474353-d23c7577-21dc-4ca7-9492-4f712bbabf62.jpg)

**Comment by ZYong9908** [comment]
![Uploading Screenshot_2023-01-14-21-34-15-072_cn.xiaochuankeji.tieba.jpg…]()

**Comment by ZYong9908** [comment]
![Uploading Screenshot_2023-01-14-21-34-15-072_cn.xiaochuankeji.tieba.jpg…]()

**Comment by ZYong9908** [comment]
![Screenshot_2023-01-14-21-46-59-624_cn xiaochuankeji tieba](https://user-images.githubusercontent.com/44081531/212475038-c83cb886-e29a-48dc-b2d0-b1cf479e11e2.jpg)
![Screenshot_2023-01-14-21-34-15-072_cn xiaochuankeji tieba](https://user-images.githubusercontent.com/44081531/212475041-f13acb52-a3cf-4550-b42c-a04e43e383e1.jpg)

**Comment by klxiaoniu** [comment]
模块版本，软件版本，运行环境提供一下

**Comment by ZYong9908** [comment]
最右 5.11.21
lsp 1.8.5
ZuiYouYook 1.1
mi11 MIUI14  A13
可能为广告的服务
`
cn.xiaochuankeji.tieba/com.bytedance.sdk.openadsdk.multipro.TTMultiProvider
cn.xiaochuankeji.tieba/com.bytedance.sdk.openadsdk.TTFileProvider
cn.xiaochuankeji.tieba/com.baidu.mobads.openad.BdFileProvider
cn.xiaochuankeji.tieba/com.bytedance.sdk.openadsdk.stub.server.DownloaderServerManager
cn.xiaochuankeji.tieba/com.bytedance.sdk.openadsdk.stub.server.MainServerManager
cn.xiaochuankeji.tieba/com.kwad.sdk.api.proxy.app.AdSdkFileProvider
cn.xiaochuankeji.tieba/com.qumeng.advlib.core.CPCFileProvider
`

**Comment by ZYong9908** [comment]
> 模块版本，软件版本，运行环境提供一下

最右 5.11.21
lsp 1.8.5
ZuiYouYook 1.1
mi11 MIUI14  A13
可能为广告的服务
`
cn.xiaochuankeji.tieba/com.bytedance.sdk.openadsdk.multipro.TTMultiProvider
cn.xiaochuankeji.tieba/com.bytedance.sdk.openadsdk.TTFileProvider
cn.xiaochuankeji.tieba/com.baidu.mobads.openad.BdFileProvider
cn.xiaochuankeji.tieba/com.bytedance.sdk.openadsdk.stub.server.DownloaderServerManager
cn.xiaochuankeji.tieba/com.bytedance.sdk.openadsdk.stub.server.MainServerManager
cn.xiaochuankeji.tieba/com.kwad.sdk.api.proxy.app.AdSdkFileProvider
cn.xiaochuankeji.tieba/com.qumeng.advlib.core.CPCFileProvider
`

**Comment by klxiaoniu** [comment]
Please update to 1.2 and see if it still happens.

**Comment by ZYong9908** [comment]
目前没有发现残留，感谢

快乐小牛 ***@***.***> 于 2023年1月28日周六 20:24写道：
